# Generated by Django 3.1 on 2021-03-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=20)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=20)),
                ('client_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfarm.user')),
            ],
        ),
        migrations.CreateModel(
            name='CallApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('time_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfarm.user')),
                ('application_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfarm.call')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfarm.user'),
        ),
    ]
