# Generated by Django 3.1 on 2021-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
