# Generated by Django 3.1 on 2021-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfarm', '0004_auto_20210311_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='applications',
            field=models.JSONField(),
        ),
    ]
